// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {settings} from '../models';

export function AddTag(arg1:number,arg2:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteItem(arg1:number):Promise<void>;

export function GetHistory(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:number):Promise<Array<db.ClipboardItem>>;

export function GetSettings():Promise<settings.AppSettings>;

export function GetStats():Promise<Record<string, any>>;

export function HideWindow():Promise<void>;

export function IsIncognito():Promise<boolean>;

export function RemoveTag(arg1:number,arg2:string):Promise<void>;

export function SaveSettings(arg1:settings.AppSettings):Promise<void>;

export function ToggleIncognito():Promise<boolean>;

export function TogglePin(arg1:number):Promise<boolean>;

export function TriggerPaste(arg1:number):Promise<void>;
