// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1, arg2) {
  return window['go']['main']['App']['AddTag'](arg1, arg2);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetHistory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsIncognito() {
  return window['go']['main']['App']['IsIncognito']();
}

export function RemoveTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveTag'](arg1, arg2);
}

export function ToggleIncognito() {
  return window['go']['main']['App']['ToggleIncognito']();
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function TriggerPaste(arg1) {
  return window['go']['main']['App']['TriggerPaste'](arg1);
}
